# Generated by Django 6.0.7 on 2026-07-15 14:43

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(default=accounts.models.default_trial_end),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(
                        default=False, help_text="Paid subscription is active."
                    ),
                ),
                ("subscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reminders_enabled",
                    models.BooleanField(
                        default=False, help_text="Send daily due-card push reminders."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
